### ISSUE TITLE
Automated new drive formatting, mounting and updating chia/plot_manger configs

### ISSUE THREAD

**Issue by rjsears** [rjsears/chia_plot_manager#38]
Code that will identify when a new drive is added to the system detecting that it is not mounted not has any partitions on it, will partition it, format it xfs, mount it, enter the required entries in /etc/fstab and update plot_manager and chia with the new mount point information.

**Comment by maxbelz** [comment]
hi, im going to use your software. thank you for this... i see this post and have a question, how can i format it to ext4? why you choose xfs vs ext4? looks like just because you are using freenas... i'd prefer ext4 cause im using directly attached hdd's (through sas expander + lsi hba controller) to my ubuntu server (which is plotter aswell). also wainting for support of multiply plotters , i have 4 plotter machines one of them is farmer aswell as plotter.

**Comment by rjsears** [comment]
It can easily be changed to utilize ext4. I use FreeNAS/TrueNAS but **NOT** on my NAS units, these are simply basic JBODs. I utilize XFS for everything associated with my Chia and ZFS for everything TrueNAS associated. I would highly recommend reading up on XFS vs ext4 before making any decisions, but frankly, either should be fine, I simply choose XFS over anything else these days unless ZFS makes sense, then I use that.....

In order for you utilize ext4 vs xfs, you would simple need to change line 215:

mkfs_results =  subprocess.run(['mkfs.xfs', '-q', '-f', drive], capture_output=True, text=True)

to:

mkfs_results =  subprocess.run(['mkfs.ext4', '-q', '-f', drive], capture_output=True, text=True)
and line 219 to this:

print(f'Process (mkfs.ext4) {green}COMPLETE{nc}!')

**Comment by maxbelz** [comment]
thank you!

**Comment by rjsears** [comment]
You bet, hope it works for you!
