### ISSUE TITLE
Fix deps in install.sh

### ISSUE THREAD

**Issue by rglastra** [rjsears/chia_plot_manager#54]
There are some more python and (in my case) apt dependencies than aren't included in install.sh currently.
For example, glances-api (does it really depend on Glances, or can this be omitted?), nc, 

Probably needs an installation on a fresh install to get the exact list. Offhand I believe I added ~5-6 python packages and ~3 packages via apt.

**Comment by rjsears** [comment]
Thank You. I will have to check and see. I test the install against a fresh install of Ubuntu 20.04 each time (via Promox VMs) so I will have to try again and make sure to add what I missed. 

The Glances is used to check and see if we are moving network traffic across the network interface where we move plots. This is just a test to make sure we are only moving one plot at a time. I am sure there are other ways to check this but since I use Glances to monitor my systems and it has an API, that is what I choose to use in this case.

Do you know which python packages were missing?
